/**
 * Copyright (c) 2008-2012, Dr. Garbage Community
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.drgarbage.bytecode;

import com.drgarbage.bytecode.constant_pool.ConstantPoolTags;
import com.drgarbage.bytecode.instructions.Opcodes;

/**
  * Byte code Constants.
  *
  * @author Sergej Alekseev and Peter Palaga
  * @version $Revision: 1523 $
  * $Id: ByteCodeConstants.java 1523 2012-04-13 14:34:24Z Sergej Alekseev $
  */
public class ByteCodeConstants implements Opcodes {
	
	public static final int MAGIC = 0xcafebabe;
	public static final String CLASS_FILE_FORMAT_VERSION = "class file format version";
	public static final String Generated_by_x = "Generated by {0}";
	public static final String Version = "Version";
	public static final String Class_retrieved_from = "Class retrieved from";

	public static final String COMPILED_FROM = "compiled from";
	public static final char UNKNOWN_INFORMATION = '?';
	
	/**
	 * The <code>'/'</code> separator character used in the class names, e.g.
	 * <code>java/lang/String</code>. 
	 */
	public static final char CLASS_NAME_SLASH = '/';
	public static final char CLASS_NAME_DOLLAR = '$';
	public static final char CLASS_NAME_POINT = '.';
	
	/**
	 * <code>"<init>"</code> - the name of the constructor methods.
	 */
	public static final String INIT = "<init>";
	
	/**
	 * <code>"<clinit>"</code> - the name of the class initialization method.
	 */
	public static final String CLINIT = "<clinit>";
	public static final char B_BYTE = 'B';
	public static final char C_CHAR = 'C';
	public static final char D_DOUBLE = 'D';
	public static final char F_FLOAT = 'F';
	public static final char I_INT = 'I';
	public static final char J_LONG = 'J';
	public static final char S_SHORT = 'S';
	public static final char Z_BOOLEAN = 'Z';
	public static final char L_REFERENCE = 'L';
	public static final char REFERENCE_TERMINATING_SEMICOLON = ';';
	public static final char ARRAY_BEGINNING_BRACKET = '[';
	public static final char V_VOID = 'V';
	public static final char METHOD_DESCRIPTOR_LEFT_PARENTHESIS = '(';
	public static final char METHOD_DESCRIPTOR_RIGHT_PARENTHESIS = ')';
	
	

    public static final String[] OPCODE_MNEMONICS;
    public static final String[] CONSTANT_POOL_TAG_MNEMONICS;
    
    static {
        
        OPCODE_MNEMONICS = new String[256];
        
        OPCODE_MNEMONICS[OPCODE_NOP] = "nop";
        OPCODE_MNEMONICS[OPCODE_ACONST_NULL] = "aconst_null";
        OPCODE_MNEMONICS[OPCODE_ICONST_M1] = "iconst_m1";
        OPCODE_MNEMONICS[OPCODE_ICONST_0] = "iconst_0";
        OPCODE_MNEMONICS[OPCODE_ICONST_1] = "iconst_1";
        OPCODE_MNEMONICS[OPCODE_ICONST_2] = "iconst_2";
        OPCODE_MNEMONICS[OPCODE_ICONST_3] = "iconst_3";
        OPCODE_MNEMONICS[OPCODE_ICONST_4] = "iconst_4";
        OPCODE_MNEMONICS[OPCODE_ICONST_5] = "iconst_5";
        OPCODE_MNEMONICS[OPCODE_LCONST_0] = "lconst_0";
        OPCODE_MNEMONICS[OPCODE_LCONST_1] = "lconst_1";
        OPCODE_MNEMONICS[OPCODE_FCONST_0] = "fconst_0";
        OPCODE_MNEMONICS[OPCODE_FCONST_1] = "fconst_1";
        OPCODE_MNEMONICS[OPCODE_FCONST_2] = "fconst_2";
        OPCODE_MNEMONICS[OPCODE_DCONST_0] = "dconst_0";
        OPCODE_MNEMONICS[OPCODE_DCONST_1] = "dconst_1";
        OPCODE_MNEMONICS[OPCODE_BIPUSH] = "bipush";
        OPCODE_MNEMONICS[OPCODE_SIPUSH] = "sipush";
        OPCODE_MNEMONICS[OPCODE_LDC] = "ldc";
        OPCODE_MNEMONICS[OPCODE_LDC_W] = "ldc_w";
        OPCODE_MNEMONICS[OPCODE_LDC2_W] = "ldc2_w";
        OPCODE_MNEMONICS[OPCODE_ILOAD] = "iload";
        OPCODE_MNEMONICS[OPCODE_LLOAD] = "lload";
        OPCODE_MNEMONICS[OPCODE_FLOAD] = "fload";
        OPCODE_MNEMONICS[OPCODE_DLOAD] = "dload";
        OPCODE_MNEMONICS[OPCODE_ALOAD] = "aload";
        OPCODE_MNEMONICS[OPCODE_ILOAD_0] = "iload_0";
        OPCODE_MNEMONICS[OPCODE_ILOAD_1] = "iload_1";
        OPCODE_MNEMONICS[OPCODE_ILOAD_2] = "iload_2";
        OPCODE_MNEMONICS[OPCODE_ILOAD_3] = "iload_3";
        OPCODE_MNEMONICS[OPCODE_LLOAD_0] = "lload_0";
        OPCODE_MNEMONICS[OPCODE_LLOAD_1] = "lload_1";
        OPCODE_MNEMONICS[OPCODE_LLOAD_2] = "lload_2";
        OPCODE_MNEMONICS[OPCODE_LLOAD_3] = "lload_3";
        OPCODE_MNEMONICS[OPCODE_FLOAD_0] = "fload_0";
        OPCODE_MNEMONICS[OPCODE_FLOAD_1] = "fload_1";
        OPCODE_MNEMONICS[OPCODE_FLOAD_2] = "fload_2";
        OPCODE_MNEMONICS[OPCODE_FLOAD_3] = "fload_3";
        OPCODE_MNEMONICS[OPCODE_DLOAD_0] = "dload_0";
        OPCODE_MNEMONICS[OPCODE_DLOAD_1] = "dload_1";
        OPCODE_MNEMONICS[OPCODE_DLOAD_2] = "dload_2";
        OPCODE_MNEMONICS[OPCODE_DLOAD_3] = "dload_3";
        OPCODE_MNEMONICS[OPCODE_ALOAD_0] = "aload_0";
        OPCODE_MNEMONICS[OPCODE_ALOAD_1] = "aload_1";
        OPCODE_MNEMONICS[OPCODE_ALOAD_2] = "aload_2";
        OPCODE_MNEMONICS[OPCODE_ALOAD_3] = "aload_3";
        OPCODE_MNEMONICS[OPCODE_IALOAD] = "iaload";
        OPCODE_MNEMONICS[OPCODE_LALOAD] = "laload";
        OPCODE_MNEMONICS[OPCODE_FALOAD] = "faload";
        OPCODE_MNEMONICS[OPCODE_DALOAD] = "daload";
        OPCODE_MNEMONICS[OPCODE_AALOAD] = "aaload";
        OPCODE_MNEMONICS[OPCODE_BALOAD] = "baload";
        OPCODE_MNEMONICS[OPCODE_CALOAD] = "caload";
        OPCODE_MNEMONICS[OPCODE_SALOAD] = "saload";
        OPCODE_MNEMONICS[OPCODE_ISTORE] = "istore";
        OPCODE_MNEMONICS[OPCODE_LSTORE] = "lstore";
        OPCODE_MNEMONICS[OPCODE_FSTORE] = "fstore";
        OPCODE_MNEMONICS[OPCODE_DSTORE] = "dstore";
        OPCODE_MNEMONICS[OPCODE_ASTORE] = "astore";
        OPCODE_MNEMONICS[OPCODE_ISTORE_0] = "istore_0";
        OPCODE_MNEMONICS[OPCODE_ISTORE_1] = "istore_1";
        OPCODE_MNEMONICS[OPCODE_ISTORE_2] = "istore_2";
        OPCODE_MNEMONICS[OPCODE_ISTORE_3] = "istore_3";
        OPCODE_MNEMONICS[OPCODE_LSTORE_0] = "lstore_0";
        OPCODE_MNEMONICS[OPCODE_LSTORE_1] = "lstore_1";
        OPCODE_MNEMONICS[OPCODE_LSTORE_2] = "lstore_2";
        OPCODE_MNEMONICS[OPCODE_LSTORE_3] = "lstore_3";
        OPCODE_MNEMONICS[OPCODE_FSTORE_0] = "fstore_0";
        OPCODE_MNEMONICS[OPCODE_FSTORE_1] = "fstore_1";
        OPCODE_MNEMONICS[OPCODE_FSTORE_2] = "fstore_2";
        OPCODE_MNEMONICS[OPCODE_FSTORE_3] = "fstore_3";
        OPCODE_MNEMONICS[OPCODE_DSTORE_0] = "dstore_0";
        OPCODE_MNEMONICS[OPCODE_DSTORE_1] = "dstore_1";
        OPCODE_MNEMONICS[OPCODE_DSTORE_2] = "dstore_2";
        OPCODE_MNEMONICS[OPCODE_DSTORE_3] = "dstore_3";
        OPCODE_MNEMONICS[OPCODE_ASTORE_0] = "astore_0";
        OPCODE_MNEMONICS[OPCODE_ASTORE_1] = "astore_1";
        OPCODE_MNEMONICS[OPCODE_ASTORE_2] = "astore_2";
        OPCODE_MNEMONICS[OPCODE_ASTORE_3] = "astore_3";
        OPCODE_MNEMONICS[OPCODE_IASTORE] = "iastore";
        OPCODE_MNEMONICS[OPCODE_LASTORE] = "lastore";
        OPCODE_MNEMONICS[OPCODE_FASTORE] = "fastore";
        OPCODE_MNEMONICS[OPCODE_DASTORE] = "dastore";
        OPCODE_MNEMONICS[OPCODE_AASTORE] = "aastore";
        OPCODE_MNEMONICS[OPCODE_BASTORE] = "bastore";
        OPCODE_MNEMONICS[OPCODE_CASTORE] = "castore";
        OPCODE_MNEMONICS[OPCODE_SASTORE] = "sastore";
        OPCODE_MNEMONICS[OPCODE_POP] = "pop";
        OPCODE_MNEMONICS[OPCODE_POP2] = "pop2";
        OPCODE_MNEMONICS[OPCODE_DUP] = "dup";
        OPCODE_MNEMONICS[OPCODE_DUP_X1] = "dup_x1";
        OPCODE_MNEMONICS[OPCODE_DUP_X2] = "dup_x2";
        OPCODE_MNEMONICS[OPCODE_DUP2] = "dup2";
        OPCODE_MNEMONICS[OPCODE_DUP2_X1] = "dup2_x1";
        OPCODE_MNEMONICS[OPCODE_DUP2_X2] = "dup2_x2";
        OPCODE_MNEMONICS[OPCODE_SWAP] = "swap";
        OPCODE_MNEMONICS[OPCODE_IADD] = "iadd";
        OPCODE_MNEMONICS[OPCODE_LADD] = "ladd";
        OPCODE_MNEMONICS[OPCODE_FADD] = "fadd";
        OPCODE_MNEMONICS[OPCODE_DADD] = "dadd";
        OPCODE_MNEMONICS[OPCODE_ISUB] = "isub";
        OPCODE_MNEMONICS[OPCODE_LSUB] = "lsub";
        OPCODE_MNEMONICS[OPCODE_FSUB] = "fsub";
        OPCODE_MNEMONICS[OPCODE_DSUB] = "dsub";
        OPCODE_MNEMONICS[OPCODE_IMUL] = "imul";
        OPCODE_MNEMONICS[OPCODE_LMUL] = "lmul";
        OPCODE_MNEMONICS[OPCODE_FMUL] = "fmul";
        OPCODE_MNEMONICS[OPCODE_DMUL] = "dmul";
        OPCODE_MNEMONICS[OPCODE_IDIV] = "idiv";
        OPCODE_MNEMONICS[OPCODE_LDIV] = "ldiv";
        OPCODE_MNEMONICS[OPCODE_FDIV] = "fdiv";
        OPCODE_MNEMONICS[OPCODE_DDIV] = "ddiv";
        OPCODE_MNEMONICS[OPCODE_IREM] = "irem";
        OPCODE_MNEMONICS[OPCODE_LREM] = "lrem";
        OPCODE_MNEMONICS[OPCODE_FREM] = "frem";
        OPCODE_MNEMONICS[OPCODE_DREM] = "drem";
        OPCODE_MNEMONICS[OPCODE_INEG] = "ineg";
        OPCODE_MNEMONICS[OPCODE_LNEG] = "lneg";
        OPCODE_MNEMONICS[OPCODE_FNEG] = "fneg";
        OPCODE_MNEMONICS[OPCODE_DNEG] = "dneg";
        OPCODE_MNEMONICS[OPCODE_ISHL] = "ishl";
        OPCODE_MNEMONICS[OPCODE_LSHL] = "lshl";
        OPCODE_MNEMONICS[OPCODE_ISHR] = "ishr";
        OPCODE_MNEMONICS[OPCODE_LSHR] = "lshr";
        OPCODE_MNEMONICS[OPCODE_IUSHR] = "iushr";
        OPCODE_MNEMONICS[OPCODE_LUSHR] = "lushr";
        OPCODE_MNEMONICS[OPCODE_IAND] = "iand";
        OPCODE_MNEMONICS[OPCODE_LAND] = "land";
        OPCODE_MNEMONICS[OPCODE_IOR] = "ior";
        OPCODE_MNEMONICS[OPCODE_LOR] = "lor";
        OPCODE_MNEMONICS[OPCODE_IXOR] = "ixor";
        OPCODE_MNEMONICS[OPCODE_LXOR] = "lxor";
        OPCODE_MNEMONICS[OPCODE_IINC] = "iinc";
        OPCODE_MNEMONICS[OPCODE_I2L] = "i2l";
        OPCODE_MNEMONICS[OPCODE_I2F] = "i2f";
        OPCODE_MNEMONICS[OPCODE_I2D] = "i2d";
        OPCODE_MNEMONICS[OPCODE_L2I] = "l2i";
        OPCODE_MNEMONICS[OPCODE_L2F] = "l2f";
        OPCODE_MNEMONICS[OPCODE_L2D] = "l2d";
        OPCODE_MNEMONICS[OPCODE_F2I] = "f2i";
        OPCODE_MNEMONICS[OPCODE_F2L] = "f2l";
        OPCODE_MNEMONICS[OPCODE_F2D] = "f2d";
        OPCODE_MNEMONICS[OPCODE_D2I] = "d2i";
        OPCODE_MNEMONICS[OPCODE_D2L] = "d2l";
        OPCODE_MNEMONICS[OPCODE_D2F] = "d2f";
        OPCODE_MNEMONICS[OPCODE_I2B] = "i2b";
        OPCODE_MNEMONICS[OPCODE_I2C] = "i2c";
        OPCODE_MNEMONICS[OPCODE_I2S] = "i2s";
        OPCODE_MNEMONICS[OPCODE_LCMP] = "lcmp";
        OPCODE_MNEMONICS[OPCODE_FCMPL] = "fcmpl";
        OPCODE_MNEMONICS[OPCODE_FCMPG] = "fcmpg";
        OPCODE_MNEMONICS[OPCODE_DCMPL] = "dcmpl";
        OPCODE_MNEMONICS[OPCODE_DCMPG] = "dcmpg";
        OPCODE_MNEMONICS[OPCODE_IFEQ] = "ifeq";
        OPCODE_MNEMONICS[OPCODE_IFNE] = "ifne";
        OPCODE_MNEMONICS[OPCODE_IFLT] = "iflt";
        OPCODE_MNEMONICS[OPCODE_IFGE] = "ifge";
        OPCODE_MNEMONICS[OPCODE_IFGT] = "ifgt";
        OPCODE_MNEMONICS[OPCODE_IFLE] = "ifle";
        OPCODE_MNEMONICS[OPCODE_IF_ICMPEQ] = "if_icmpeq";
        OPCODE_MNEMONICS[OPCODE_IF_ICMPNE] = "if_icmpne";
        OPCODE_MNEMONICS[OPCODE_IF_ICMPLT] = "if_icmplt";
        OPCODE_MNEMONICS[OPCODE_IF_ICMPGE] = "if_icmpge";
        OPCODE_MNEMONICS[OPCODE_IF_ICMPGT] = "if_icmpgt";
        OPCODE_MNEMONICS[OPCODE_IF_ICMPLE] = "if_icmple";
        OPCODE_MNEMONICS[OPCODE_IF_ACMPEQ] = "if_acmpeq";
        OPCODE_MNEMONICS[OPCODE_IF_ACMPNE] = "if_acmpne";
        OPCODE_MNEMONICS[OPCODE_GOTO] = "goto";
        OPCODE_MNEMONICS[OPCODE_JSR] = "jsr";
        OPCODE_MNEMONICS[OPCODE_RET] = "ret";
        OPCODE_MNEMONICS[OPCODE_TABLESWITCH] = "tableswitch";
        OPCODE_MNEMONICS[OPCODE_LOOKUPSWITCH] = "lookupswitch";
        OPCODE_MNEMONICS[OPCODE_IRETURN] = "ireturn";
        OPCODE_MNEMONICS[OPCODE_LRETURN] = "lreturn";
        OPCODE_MNEMONICS[OPCODE_FRETURN] = "freturn";
        OPCODE_MNEMONICS[OPCODE_DRETURN] = "dreturn";
        OPCODE_MNEMONICS[OPCODE_ARETURN] = "areturn";
        OPCODE_MNEMONICS[OPCODE_RETURN] = "return";
        OPCODE_MNEMONICS[OPCODE_GETSTATIC] = "getstatic";
        OPCODE_MNEMONICS[OPCODE_PUTSTATIC] = "putstatic";
        OPCODE_MNEMONICS[OPCODE_GETFIELD] = "getfield";
        OPCODE_MNEMONICS[OPCODE_PUTFIELD] = "putfield";
        OPCODE_MNEMONICS[OPCODE_INVOKEVIRTUAL] = "invokevirtual";
        OPCODE_MNEMONICS[OPCODE_INVOKESPECIAL] = "invokespecial";
        OPCODE_MNEMONICS[OPCODE_INVOKESTATIC] = "invokestatic";
        OPCODE_MNEMONICS[OPCODE_INVOKEINTERFACE] = "invokeinterface";
        OPCODE_MNEMONICS[OPCODE_INVOKEDYNAMIC] = "invokedynamic";
        OPCODE_MNEMONICS[OPCODE_NEW] = "new";
        OPCODE_MNEMONICS[OPCODE_NEWARRAY] = "newarray";
        OPCODE_MNEMONICS[OPCODE_ANEWARRAY] = "anewarray";
        OPCODE_MNEMONICS[OPCODE_ARRAYLENGTH] = "arraylength";
        OPCODE_MNEMONICS[OPCODE_ATHROW] = "athrow";
        OPCODE_MNEMONICS[OPCODE_CHECKCAST] = "checkcast";
        OPCODE_MNEMONICS[OPCODE_INSTANCEOF] = "instanceof";
        OPCODE_MNEMONICS[OPCODE_MONITORENTER] = "monitorenter";
        OPCODE_MNEMONICS[OPCODE_MONITOREXIT] = "monitorexit";
        OPCODE_MNEMONICS[OPCODE_WIDE] = "wide";
        OPCODE_MNEMONICS[OPCODE_MULTIANEWARRAY] = "multianewarray";
        OPCODE_MNEMONICS[OPCODE_IFNULL] = "ifnull";
        OPCODE_MNEMONICS[OPCODE_IFNONNULL] = "ifnonnull";
        OPCODE_MNEMONICS[OPCODE_GOTO_W] = "goto_w";
        OPCODE_MNEMONICS[OPCODE_JSR_W] = "jsr_w";
        OPCODE_MNEMONICS[OPCODE_BREAKPOINT] = "breakpoint";
        OPCODE_MNEMONICS[OPCODE_IMPDEP1] = "impdep1";
        OPCODE_MNEMONICS[OPCODE_IMPDEP2] = "impdep2";
        
        
        CONSTANT_POOL_TAG_MNEMONICS = new String[19];
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_CLASS] = "CONSTANT_Class";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_FIELDREF] = "CONSTANT_Fieldref";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_METHODREF] = "CONSTANT_Methodref";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_INTERFACE_METHODREF] = "CONSTANT_InterfaceMethodref";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_STRING] = "CONSTANT_String";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_INTEGER] = "CONSTANT_Integer";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_FLOAT] = "CONSTANT_Float";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_LONG] = "CONSTANT_Long";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_DOUBLE] = "CONSTANT_Double";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_NAME_AND_TYPE] = "CONSTANT_NameAndType";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_UTF8] = "CONSTANT_Utf8";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_METHOD_HANDLE] = "CONSTANT_MethodHandle";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_METHOD_TYPE] = "CONSTANT_MethodType";
        CONSTANT_POOL_TAG_MNEMONICS[ConstantPoolTags.CONSTANT_INVOKE_DYNAMIC] = "CONSTANT_InvokeDynamic";

    }
    
    public static final int INVALID_OFFSET = -1;
	public static final String JAVA = "java";
	
	public static final String JAVA_LANG_OBJECT = "java/lang/Object";
	public static final String DEBUG_INFO = "debug info";
	public static final String JAVA_LANG_DEPRECATED = "java/lang/Deprecated";
	public static final String BRIDGE_METHOD_GENERATED_BY_THE_COMPILER = "bridge method generated by the compiler";
	public static final String ARG = "arg";
	public static final String SOURCE_LINE = "source line";
	public static final byte TAG_CLASS = 7;
	public static final byte TAG_FIELDREF = 9;
	public static final byte TAG_METHODREF = 10;
	public static final byte TAG_INTERFACE_METHODREF = 11;
	public static final byte TAG_STRING = 8;
	public static final byte TAG_INTEGER = 3;
	public static final byte TAG_FLOAT = 4;
	public static final byte TAG_LONG = 5;
	public static final byte TAG_DOUBLE = 6;
	public static final byte TAG_NAME_AND_TYPE = 12;
	public static final byte TAG_UTF8 = 1;
	public static final byte TAG_METHOD_HANDLE = 15;
	public static final byte TAG_METHOD_TYPE = 16;
	public static final byte TAG_INVOKE_DYNAMIC = 18;
	public static final String COVERS_BYTES_X_TO_Y = "covers bytes {0} to {1}";
	public static final String INNER_CLASS = "inner class";
	public static final String LINE_NUMBER_TABLE = "LineNumberTable";
	public static final String LINE_NUMBER_TABLE_NOT_AVAILABLE = "LineNumberTable not available";
	public static final String LOCAL_VARIABLE_TABLE = "LocalVariableTable";
	public static final String LOCAL_VARIABLE_TYPE_TABLE = "LocalVariableTypeTable";
	public static final String CODE = "Code";

	public static final String START_PC = "start_pc";
	public static final String LINE = "line";
	public static final Object LOCAL_VARIABLE_TABLE_NOT_AVAILABLE = "LocalVariableTable not available";
	public static final Object LOCAL_VARIABLE_TABLE_EMPTY = "LocalVariableTable (empty)";
	public static final Object LOCAL_VARIABLE_TYPE_TABLE_NOT_AVAILABLE = "LocalVariableTypeTable not available";
	public static final String LENGTH = "length";
	public static final String NAME_INDEX = "name_index";
	public static final String DESCRIPTOR_INDEX = "descriptor_index";
	public static final String INDEX = "index";
	public static final String NAME = "name";
	public static final String DESCRIPTOR = "descriptor";
	public static final String LINE_NUMBER = "line_number";
	public static final String CLINIT_MNEMONICS = "{...}";
	public static final String OUTER_CLASS = "outer class";
	public static final String IN_METHOD = "in method";
	public static final String VISIBLE = "visible";
	public static final String INVISIBLE = "invisible";
	public static final String ANNOTATION = "annotation";
	public static final String ATTRIBUTE = "attribute";
	public static final int INVALID_LINE = -1;
	public static final String JDI = "JDI";
	public static final String Filesystem = "Filesystem";
	public static final String TYPE_AND_NAME = "type and name";
	public static final String VARARGS = "varargs";
	public static final String LOADED_INNER_TYPES = "Loaded inner types:";
	public static final String Debug_target = "Debug target";
	public static final String Retrieved_on = "Retrieved on";
	public static final String ID = "id";
	public static final String CONSTANT_POOL_NOT_AVAILABLE = "Constant Pool not available";
	public static final String CONSTANT_POOL = "Constant Pool";
	public static final String CONSTANT_POOL_EMPTY = "Constant Pool (empty)";
	public static final String TAG = "tag";
	public static final String INFO = "info";
	public static final String CLASS_INDEX = "class_index";
	public static final String name_and_type_index = "name_and_type_index";
	public static final String string_index = "string_index";
	public static final String bytes = "bytes";
	public static final char L_LINE = 'L';
	public static final String METHOD_HANDLE_REF_KIND = "reference_kind";
	public static final String METHOD_HANDLE_INDEX = "reference_index";
	public static final String INVOKE_DYNAMIC_BOOTSTRAP_METHOD_ATTR_INDEX = "bootstrap_method_attr_index";
	public static final String INVOKE_DYNAMIC_NAME_AND_TYPE_INDEX = "name_and_type_index";

	public static enum Align {LEFT, CENTER, RIGHT};  
    
}
